Algoritmo "conversorAngulo"

Var
angulo, s, c, t: real


Inicio

Escreva("Digite o ângulo em graus: ")
Leia(angulo)
s <- Int (Sen (GraupRad (angulo)))
Escreval("O seno do Ângulo", angulo, " graus é igual a ")

c <- Int (Cos (GraupRad (angulo)))
Escreval("O cosseno do Ângulo", angulo, " graus é igual a ")

t <- Int (Tan (GraupRad (angulo)))
Escreval("O tangente do Ângulo", angulo, " graus é igual a ")

Fimalgoritmo